version: '3.7'

services:
  postgres:
    image: postgres:14.1
    ports:
      - '8090:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: trelloappclone
      POSTGRES_PASSWORD: "AeWr7jC6auPP8M0pewBKvp6P-14WKTkB"
    volumes:
      - trelloappclone_data:/var/lib/postgresql/data
  redis:
    image: redis:6.2.6
    ports:
      - '8091:6379'
    command: redis-server --requirepass "X3tfQSHnltsa-yx8badihKv1tU2in9OV"
    environment:
      - REDIS_REPLICATION_MODE=master
volumes:
  trelloappclone_data:
